version: '3.4'

services:
  api:
    container_name: api
    build:
      context: .
      target: dev
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:3000
    environment:
      - MONGODB_CONNSTRING=mongodb://mongo:${MONGODB_PORT}/${MONGODB_DATABASE}
    command: npm run dev
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - .env
    ports:
      - '${MONGODB_PORT}:27017'
    volumes:
      - dbdata-volume:/data/db
    environment:
      - MONGO_INITDB_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGODB_PASSWORD}
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
    links:
      - mongo
volumes:
  dbdata-volume:
